# Generated by Django 2.2.3 on 2019-07-03 22:11

from django.db import migrations, models
import django.db.models.deletion
import shop.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24)),
                ('picture', models.ImageField(blank=True, max_length=255, upload_to='category_pictures/', validators=[shop.validators.validate_file_size])),
                ('background', models.ImageField(blank=True, max_length=255, upload_to='background/', validators=[shop.validators.validate_file_size])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, max_length=255, upload_to='product_pictures/', validators=[shop.validators.validate_file_size])),
                ('title', models.CharField(max_length=48)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('amount', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
        ),
    ]
