# Generated by Django 2.2.3 on 2019-07-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='timezone.now()', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(default='00:00:00', max_length=120),
        ),
    ]
