# Generated by Django 2.2.3 on 2019-07-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190710_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(default='timezone.now()', max_length=300),
            preserve_default=False,
        ),
    ]
